# Generated by Django 2.2.19 on 2021-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hvhjvjhv',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='ttt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
